# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [3]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [4]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [5]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [16]:
keras.backend.clear_session()

il = keras.layers.Input(shape = (1,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(il,ol)

model.compile(loss = keras.losses.mean_squared_error,
             optimizer = 'adam',
             )

In [17]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 389ms/step - loss: 229.0593
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 228.6973
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 228.3357
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 227.9743
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 227.6133
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 227.2526
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 226.8921
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 226.5320
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 226.1722
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 225.8128


In [18]:
print(y)
print(model.predict(x).reshape(-1,) )

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[ 9.99734830e-03 -1.28296459e+00 -2.57592654e+00 -3.86888838e+00
 -5.16185045e+00 -6.45481253e+00 -7.74777412e+00 -9.04073620e+00
 -1.03336983e+01 -1.16266603e+01 -1.29196224e+01 -1.42125845e+01
 -1.55055456e+01 -1.67985096e+01 -1.80914707e+01 -1.93844337e+01
 -2.06773949e+01 -2.19703560e+01 -2.32633190e+01 -2.45562801e+01]


## Quick Logistic Regression!

In [9]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [10]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [11]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [12]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 1s 552ms/step - loss: 2.3615 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 2.3544 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 2.3472 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 2.3400 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 2.3328 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 2.3256 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 2.3185 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 2.3113 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 2.3041 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 2.2970 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 

## Now, Your turn!

In [2]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [4]:
keras.backend.clear_session()

il = keras.layers.Input(shape = (1,))
ol = keras.layers.Dense(1, activation = 'sigmoid')(il)

model = keras.models.Model(il, ol)

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [5]:
model.fit(x,y, epochs=10, verbose = 1)

Epoch 1/10
2/2 [==============================] - 1s 6ms/step - loss: 4.7771 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 6ms/step - loss: 4.7667 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 6ms/step - loss: 4.7561 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 4.7461 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 6ms/step - loss: 4.7357 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 4.7251 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 5ms/step - loss: 4.7152 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 6ms/step - loss: 4.7046 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 7ms/step - loss: 4.6944 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 6ms/step - loss: 4.6841 - accuracy: 0.5250


In [6]:
print(y)
print(model.predict(x).reshape(-1,) ) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
[0.49500993 0.72307396 0.87429535 0.9487877  0.9801388  0.9924502
 0.99715227 0.998929   0.99959767 0.99984884 0.99994314 0.99997866
 0.9999921  0.999997   0.9999989  0.9999996  1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.        ]
