# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [45]:
from sklearn.datasets import load_boston

In [46]:
boston = load_boston()

In [47]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [48]:
x.shape, y.shape

((506, 13), (506,))

In [49]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(13,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(il,ol)

model.compile(loss = 'mse',
             optimizer = 'adam')


In [88]:
model.fit(x, y, epochs=100, verbose = 1)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 25.7147
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 25.7225
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 25.6298
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 25.8983
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 25.9672
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 25.5854
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 26.1973
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 25.8839
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 25.5239
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 25.6845
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 25.8641
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 25.5862
Epoch 13/100
16/16 [=====

In [89]:
print(y[:5])
print(model.predict(x)[:5].reshape(-1,) )

[24.  21.6 34.7 33.4 36.2]
[29.2905   24.481781 30.332031 29.569431 28.985268]


# Logistic Regression 쬐금 더 어려운 데이터

In [33]:
from sklearn.datasets import load_breast_cancer

In [34]:
cancer = load_breast_cancer()

In [35]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것

In [36]:
x.shape, y.shape

((569, 30), (569,))

In [37]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation = 'sigmoid')(il)

model = keras.models.Model(il, ol)

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [42]:
model.fit(x, y, epochs=10, verbose = 1)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9872 - accuracy: 0.9086
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9809 - accuracy: 0.9139
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9804 - accuracy: 0.9086
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9722 - accuracy: 0.9139
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9719 - accuracy: 0.9104
Epoch 6/10
18/18 [==============================] - 0s 3ms/step - loss: 0.9697 - accuracy: 0.9086
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9543 - accuracy: 0.9121
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9517 - accuracy: 0.9104
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9467 - accuracy: 0.9139
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9410 - accuracy: 0.9121


In [43]:
print(y[:5])
print(model.predict(x)[:5].reshape(-1,) )

[0 0 0 0 0]
[0.0000000e+00 0.0000000e+00 1.8165842e-38 9.9964583e-01 5.1465745e-17]
