# 멀티클래스 분류 연습 (over 2진분류)

![iris_flower](https://media.istockphoto.com/photos/purple-iris-flowers-picture-id974833780?k=6&m=974833780&s=612x612&w=0&h=xANkJjTqlLuJUMLE0qNXjRUqXtr3b428xFm0IgZW8Kc=)

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [8]:
y = to_categorical(y, 3)

In [9]:
x.shape, y.shape

((150, 4), (150, 3))

# 1번. Sequential API style로 모델링 하세요

    loss = 'categorical_crossentropy' 사용!

In [12]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

In [11]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(3, activation = 'sigmoid') )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(13,)) )

# 4번 컴파일 
model.compile(loss='categorical_crossentropy',                
              optimizer='adam',
             metrics=['accuracy'])          


In [12]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 1s 3ms/step - loss: 1.6841 - accuracy: 0.0133
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 1.6404 - accuracy: 0.0200
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 1.6020 - accuracy: 0.0267
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 1.5658 - accuracy: 0.0267
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 1.5304 - accuracy: 0.0333
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 1.4986 - accuracy: 0.0400
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 1.4678 - accuracy: 0.0533
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 1.4425 - accuracy: 0.0733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 1.4213 - accuracy: 0.0800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3975 - accuracy: 0.1067


In [14]:
y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.7092429 , 0.8942089 , 0.7309989 , 0.7527679 , 0.8789332 ,
       0.7609056 , 0.6990868 , 0.87614286, 0.7170405 , 0.67085207,
       0.8572155 , 0.7071159 , 0.67385966, 0.8904667 , 0.7059276 ],
      dtype=float32)

In [17]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# 2번. Functional API style로 모델링 하세요

In [10]:
x.shape, y.shape

((150, 4), (150, 3))

In [22]:
keras.backend.clear_session()

il = keras.layers.Input(shape = (4,))
ol = keras.layers.Dense(3, activation = 'softmax')(il)

model = keras.models.Model(il, ol)

model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [23]:
model.fit(x,y, epochs=10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 3.0082 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 2.9559 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 2.9076 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 2.8595 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 2.8126 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 2.7688 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7254 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6865 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 2.6441 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 2.6075 - accuracy: 0.3333


In [24]:
y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.17802306, 0.31168237, 0.5102945 , 0.20100503, 0.21487953,
       0.5841155 , 0.19165552, 0.3053935 , 0.50295097, 0.21636112,
       0.2570327 , 0.52660614, 0.17499371, 0.3544632 , 0.47054306],
      dtype=float32)

In [25]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)